# import enchant
from HomeDepotCSVReader import HomeDepotReader
from HomeDepotCSVWriter import HomeDepotCSVWriter
import FeatureEngineering
import pandas as pd
import re
from collections import defaultdict
import numpy as np
import nltk
import string


spell_dict ={
'aacessories' : 'accessories',
'abresive' : 'adhesive',
'ac/heat' : 'air conditioner heater',
'ac/hehat' : 'air conditioner heater',
'acccessories' : 'accessories',
'accecories' : 'accessories',
'accesores' : 'accessories',
'accesories' : 'accessories',
'accesorios' : 'accessories',
'accesory' : 'accessories',
'accsesories' : 'accessories',
'accunts' : 'accounts',
'acessary' : 'accessories',
'ackup' : 'backup',
'acrilic' : 'acrylic',
'acrtlic' : 'acrylic',
'acryl' : 'acrylic',
'acryllic' : 'acrylic',
'adaapter' : 'adapter',
'adapator' : 'adapter',
'addhesion' : 'adhesion',
'addison' : 'addition',
'adheasive' : 'adhesive',
'adhensive' : 'adhesive',
'adhesiv' : 'adhesive',
'adi' : 'aid',
'adjustable\'' : 'adjustable',
'adrone' : 'drone',
'advantium' : 'advantage',
'aera' : 'area',
'aeretor' : 'aerator',
'aftificial' : 'artificial',
'agapter' : 'adapter',
'air-tit' : 'airtight',
'airator' : 'aerator',
'aircare' : 'haircare',
'aircondiioner' : 'air conditioner',
'aircondition' : 'air conditioner',
'airconditioner' : 'air conditioner',
'airconditionerwith' : 'air conditioner',
'airens' : 'sirens',
'airfilter' : 'air filter',
'airgap' : 'air gap',
'airguard' : 'air guard',
'airhose' : 'air hose',
'airnailer' : 'air nailer',
'airosol' : 'aerosol',
'airvents' : 'air vents',
'albow' : 'elbow',
'alerty' : 'alert',
'alexandrea' : 'alexandre',
'aligator' : 'alligator',
'alium' : 'alum',
'alluminum' : 'aluminum',
'alluminun' : 'aluminum',
'aluimin' : 'aluminum',
'alumanam' : 'aluminum',
'aluminuim' : 'aluminum',
'aluminumm' : 'aluminum',
'aluminun' : 'aluminum',
'alumium' : 'aluminum',
'alumiun' : 'alumina',
'alumiunm' : 'aluminum',
'aluninion' : 'aluminum',
'alvin' : 'aluminum',
'ampweather' : 'amp weather',
'anchor/bolts' : 'anchor bolts',
'anntenias' : 'antennas',
'anti-bacterial' : 'antibacterial',
'apec' : 'pace',
'aple' : 'pale',
'apoxy' : 'epoxy',
'appearnce' : 'appearance',
'apper' : 'paper',
'aprent' : 'parent',
'aqg' : 'avg',
'aqua/turquoise' : 'aqua turquoise',
'aquaia' : 'aquatic',
'arcfault' : 'arc fault',
'architecs' : 'architects',
'archor' : 'anchor',
'ardex' : 'arden',
'arearugs' : 'area rugs',
'arien' : 'arisen',
'arietta' : 'marietta',
'arkers' : 'anchor',
'armorguard' : 'armor guard',
'armstroung' : 'armstrong',
'aromasteam' : 'aroma steam',
'aromaticeatern' : 'aromaticness',
'artesia' : 'asteria',
'artifical' : 'artificial',
'artric' : 'article',
'asana' : 'asama',
'asathbula' : 'flash bulb',
'ashburn' : 'washburn',
'ashfield' : 'ash field',
'ashingles' : 'shingles',
'ashphalt' : 'asphalt',
'ashwell' : 'ash well',
'ashwood' : 'ash wood',
'askley' : 'ashley',
'askoll' : 'aspell',
'aspectmetal' : 'aspect metal',
'asphaul' : 'asphalt',
'asphault' : 'asphalt',
'aspiradora' : 'aspirator',
'assesories' : 'accessories',
'assessories' : 'accessories',
'assie' : 'accessories',
'assorment' : 'assortment',
'atachments' : 'attachments',
'atanderd' : 'standard',
'atatchment' : 'attachment',
'atlantiic' : 'atlantic',
'atomatica' : 'automatically',
'attactchent' : 'attachment',
'attatchmens' : 'attachments',
'atttic' : 'attic',
'auqatic' : 'aquatic',
'autofeeder' : 'auto feeder',
'autoficial' : 'artificial',
'autom' : 'automatic',
'automatice' : 'automatic',
'automotive-grade' : 'automotive',
'avanti' : 'avant',
'awap' : 'swap',
'b&d' : 'black and decker',
'baag' : 'bag',
'babkpack' : 'backpack',
'backbrace' : 'back brace',
'backet' : 'bracket',
'backpocket' : 'back pocket',
'backsp' : 'back splash',
'backspl' : 'back splash',
'backsplach' : 'back splash',
'badless' : 'back splash',
'bag,' : 'bag',
'baint' : 'bait',
'bakewarte' : 'bakelite',
'balde' : 'blade',
'barackets' : 'brackets',
'barreir' : 'barrier',
'barrells' : 'barrier',
'barriar' : 'barrier',
'basco' : 'basso',
'baseboarders' : 'base boarders',
'baseboarrd' : 'baseboard',
'basebord' : 'baseboard',
'baseket' : 'basket',
'basem' : 'base',
'basemetnt' : 'basement',
'bassment' : 'basement',
'bateries' : 'batteries',
'batery' : 'batteries',
'bath/shower' : 'bath shower',
'batharoom' : 'bathroom',
'bathfan' : 'bath fan',
'bathfans' : 'bath fan',
'bathro' : 'bathroom',
'bathroomvanity' : 'bathroom vanity',
'bathroon' : 'bathroom',
'bathrub' : 'bathtub',
'bathtub/shower' : 'bathtub',
'bathtubdoor' : 'bathtub door',
'bathtubes' : 'bathtub',
'bathtup' : 'bathtub',
'bathub' : 'bathtub',
'bathun' : 'bathtub',
'batroom' : 'bathroom',
'batte' : 'batch',
'batterie' : 'batteries',
'batteried' : 'batteries',
'battery,' : 'batteries',
'battery-powered' : 'batteries',
'batteryfor' : 'batteries for',
'battey' : 'batteries',
'batties' : 'batteries',
'battrey' : 'batteries',
'battub' : 'bathtub',
'battwery' : 'batteries',
'baulaster' : 'blaster',
'baxksplash' : 'back splash',
'bayonett' : 'bayonet',
'baysolar' : 'bay solar',
'bbrush' : 'brush',
'beachwood' : 'beechwood',
'beadex' : 'beaded',
'beadez' : 'beaded',
'bedroom/' : 'bedroom',
'beekman' : 'beermat',
'behrwooden' : 'woodenness',
'beige,' : 'beige',
'beige/black' : 'beige black',
'bellbox' : 'bell box',
'bello' : 'bell',
'beltsr' : 'belts',
'bemch' : 'beech',
'bemis' : 'semis',
'bench,' : 'bench',
'beneto' : 'benetton',
'berh' : 'herb',
'berhr' : 'berth',
'bermingham' : 'birmingham',
'beveragecooler' : 'beverage cooler',
'bfush' : 'brush',
'bibbs' : 'bibs',
'bicyclestorage' : 'bicycle storage',
'bidat' : 'bidet',
'biech' : 'beech',
'biege' : 'beige',
'bieges' : 'beige',
'biinds' : 'blind',
'bilnd' : 'blind',
'bisquit' : 'biscuit',
'bit,' : 'bit',
'bitt' : 'bit',
'biview' : 'bi view',
'blabes' : 'blade',
'blace' : 'blade',
'black/ivory' : 'black ivory',
'blackspash' : 'back splash',
'blad' : 'bald',
'blades,' : 'blades',
'blakck' : 'black',
'blanco' : 'blanc',
'blanv' : 'blanc',
'blash' : 'splash',
'blasplash' : 'black splash',
'blcktop' : 'blacktop',
'blde' : 'bled',
'bldes' : 'blades',
'blinds/' : 'blinds',
'blk' : 'block',
'blodks' : 'blocks',
'blong' : 'long',
'bloowers' : 'blowers',
'blower/mulchers' : 'blower',
'blower/vacuum' : 'blower vacuum',
'blowerr' : 'blower',
'bluwood' : 'bellwood',
'bmboo' : 'bamboo',
'bnasket' : 'basket',
'boack' : 'black',
'boader' : 'broader',
'boaed' : 'boated',
'boardman' : 'board man',
'boards,' : 'boards',
'board~' : 'board',
'boc' : 'cob',
'boch' : 'botch',
'bolt,' : 'bolt',
'bome' : 'some',
'bonda' : 'honda',
'bondo' : 'honda',
'bookc' : 'book',
'bootz' : 'boot',
'borsh' : 'bosch',
'bosch,' : 'bosch',
'bosche' : 'bosch',
'boscj' : 'bosch',
'boscobel' : 'bosch',
'boshe' : 'bosch',
'bosss' : 'boss',
'boundle' : 'bundle',
'bousch' : 'boucher',
'boxes,' : 'boxes',
'boxs' : 'boxes',
'boz' : 'boxes',
'bplanked' : 'planked',
'bprder' : 'border',
'bq' : 'bbq',
'bracker' : 'bracket',
'brackest' : 'bracket',
'brackt' : 'bracket',
'braker' : 'bracket',
'brakers' : 'bracket',
'braket' : 'bracket',
'brakets' : 'bracket',
'brasscraft' : 'brass craft',
'braxilian' : 'brazilian',
'breaker,' : 'breaker',
'breakers,' : 'breakers',
'brentwood' : 'bentwood',
'broil-mate' : 'broil',
'bronse' : 'bronze',
'bronz' : 'bronze',
'bronza' : 'bronze',
'bronze,' : 'bronze',
'bronzel' : 'bronze',
'bronzw' : 'bronze',
'browel' : 'blower',
'browj' : 'bronze',
'brown-beige' : 'brown beige',
'brown/goldroyalty' : 'brown',
'brown/ivory' : 'brown ivory',
'brownbrick' : 'brown brick',
'brownswitch' : 'brown switch',
'brushes,' : 'brushes',
'brushles' : 'brushes',
'bti' : 'btu',
'btuair' : 'btu air',
'btype' : 'type',
'bubles' : 'baubles',
'buckes' : 'buckets',
'buddahs' : 'buddhas',
'bufflo' : 'buffalo',
'buiding' : 'building',
'buikids' : 'builds',
'builco' : 'buildup',
'buildng' : 'building',
'built-in' : 'built',
'buisk' : 'busk',
'buit' : 'boot',
'bulb:' : 'bulb',
'bulbl' : 'bulb',
'bulbs,' : 'bulb',
'bulbsbulbs' : 'bulb',
'buld' : 'bulb',
'bullbs' : 'bulbs',
'bulp' : 'bulb',
'bungee-cords' : 'bungees',
'bungie' : 'bungees',
'bunn' : 'bun',
'bunners' : 'runners',
'burgluar' : 'burglar',
'burgondy' : 'burglar',
'burgular' : 'burglar',
'buring' : 'bring',
'burnerner' : 'burner',
'burners,' : 'burners',
'bushbutton' : 'pushbutton',
'bussmann' : 'businessman',
'buth' : 'booth',
'butto' : 'butt',
'bvolt' : 'volt',
'byass' : 'bass',
'byefold' : 'bi fold',
'byfold' : 'bi fold',
'byrgundy' : 'burgundy',
'caamera' : 'camera',
'cabi' : 'cabinet',
'cabibet' : 'cabinet',
'cabients' : 'cabinet',
'cabinate' : 'cabinet',
'cabinent' : 'cabinet',
'cabinents' : 'cabinet',
'cabiner' : 'cabinet',
'cabines' : 'cabinet',
'cabinets-' : 'cabinet',
'cabinetscornor' : 'cabinet',
'cabinett' : 'cabinet',
'cabinetupper' : 'cabinet upper',
'cabinetwithouttops' : 'cabinet without top',
'cabinte' : 'cabinet',
'cabintes' : 'cabinet',
'cabl' : 'cable',
'cable,' : 'cable',
'cablee' : 'cable',
'cablenail' : 'cable nail',
'cablrail' : 'cable rail',
'cabnet' : 'cabinet',
'cabnets' : 'cabinets',
'cabnetsn' : 'cabernet',
'cabniets' : 'cabinets',
'cabnit' : 'cabinet',
'cabo' : 'cab',
'cabrio' : 'cabriolet',
'cadetcordless' : 'cadet cordless',
'cahnnel' : 'channel',
'cair' : 'hair',
'camaras' : 'cameras',
'cambria' : 'cambric',
'cambrige' : 'cambridge',
'cammera' : 'camera',
'camoflogue' : 'camouflage',
'candels' : 'candles',
'candlabra' : 'candelabra',
'candlebra' : 'candle bra',
'caninet' : 'canine',
'canopie' : 'canopies',
'canoply' : 'canopy',
'canspot' : 'can spot',
'canster' : 'caster',
'capacitator' : 'capacitor',
'carbrator' : 'calibrator',
'carburator' : 'carburetor',
'cardell' : 'car dell',
'carlo' : 'carol',
'carpert' : 'carpet',
'carpetshampoo' : 'carpet shampoo',
'carpot' : 'carpet',
'carpt' : 'carpet',
'cartidges' : 'cartridges',
'cartridges,' : 'cartridges',
'cartrigdge' : 'cartridge',
'caryon' : 'crayon',
'cas' : 'case',
'casa' : 'case',
'cascadia' : 'cascades',
'caseing' : 'casing',
'cass' : 'case',
'castiron' : 'cast iron',
'catchbag' : 'catch bag',
'catridges' : 'cartridges',
'cbinet' : 'cabinet',
'ccurved' : 'curved',
'ceadar' : 'cedar',
'ceader' : 'ceder',
'cealing' : 'sealing',
'cedan' : 'sedan',
'cedar-tone' : 'cedar',
'ceilig' : 'ceiling',
'ceilikng' : 'ceiling',
'ceilin' : 'ceiling',
'ceilng' : 'ceiling',
'ceing' : 'ceiling',
'celin' : 'ceiling',
'celing' : 'ceiling',
'celliling' : 'ceiling',
'cellofoam' : 'cello foam',
'celullar' : 'cellular',
'cement,' : 'cement',
'cemet' : 'cement',
'cemnt' : 'cement',
'cender' : 'ender',
'centerpise' : 'centerpiece',
'centerset,' : 'centerline',
'ceramic,' : 'ceramic',
'ceramick' : 'ceramic',
'cermic' : 'ceramic',
'chages' : 'charge',
'chaincome' : 'chain come',
'chainlink' : 'chain link',
'chair,' : 'chair',
'chamber-top' : 'chamberpot',
'chandalier' : 'chandelier',
'chandielier' : 'chandelier',
'chandilier' : 'chandelier',
'chann' : 'chain',
'channe' : 'channel',
'channellock' : 'channel lock',
'chanpayne' : 'channeler',
'chaosaw' : 'chaos aw',
'char-broil' : 'charbroil',
'charbroi' : 'charbroil',
'charcole' : 'charcoal',
'chargril' : 'chargrill',
'charllotesville' : 'charlottesville',
'charlston' : 'charleston',
'charolettetown' : 'charlottetown',
'chesnut' : 'chestnut',
'chessnut' : 'chestnut',
'chian' : 'chain',
'chissel' : 'chisel',
'choc' : 'soc',
'chome' : 'chrome',
'chopsaw' : 'chop saw',
'chrismas' : 'chrisms',
'christmass' : 'christmas',
'christmsa' : 'christmas',
'chrisymas' : 'christmas',
'chritmas' : 'christmas',
'chritsmas' : 'christmas',
'chritstmas' : 'christmas',
'chrome-plated' : 'chrome plated',
'chrome/polished' : 'chrome polished',
'cicular' : 'circular',
'ciding' : 'dicing',
'cieling' : 'ceiling',
'cielings' : 'ceilings',
'ciling' : 'sling',
'cilynder' : 'cylinder',
'cimeron' : 'cameron',
'cinamon' : 'cinnamon',
'cincking' : 'zincking',
'circlular' : 'circular',
'circualtor' : 'circulatory',
'circuline' : 'circulant',
'circut' : 'circuit',
'circute' : 'circuit',
'clab' : 'lab',
'clacer' : 'lacer',
'clacier' : 'lacier',
'clades' : 'lades',
'claissic' : 'classic',
'clarifer,' : 'clarifier',
'classico' : 'classic',
'cleanaer' : 'cleaner',
'cleane' : 'clean',
'cleaner,' : 'cleaner',
'cleaneraner' : 'cleaner',
'cleanere' : 'cleaner',
'cleanerm' : 'cleaner',
'cleaninig' : 'cleaning',
'clicklock' : 'click lock',
'clip-on' : 'clipping',
'clopay' : 'copay',
'clopay,' : 'clopped',
'clorine' : 'chlorine',
'closermaid' : 'closer maid',
'closetmade' : 'closet made',
'closetr' : 'closet',
'closit' : 'closet',
'clothsline' : 'clothesline',
'cmbo' : 'combo',
'co/fire' : 'crossfire',
'coatracks' : 'coat racks',
'cobwoys' : 'cowboys',
'coccrete' : 'concrete',
'coedless' : 'cordless',
'cointertop' : 'countertop',
'colared' : 'collared',
'colerful' : 'colorful',
'collecion' : 'collection',
'collectin' : 'collection',
'collectionchrome' : 'collection chrome',
'coller' : 'color',
'collor' : 'color',
'collors' : 'colors',
'color:' : 'color',
'colores' : 'colors',
'colorhouse' : 'color house',
'colth' : 'cloth',
'colum' : 'column',
'colunm' : 'column',
'combon' : 'combo',
'comealong' : 'come along',
'comercial' : 'commercial',
'comercialcarpet' : 'comercial carpet',
'commercail' : 'commercial',
'commercil' : 'commercial',
'commerial' : 'commercial',
'compactorr' : 'compactor',
'compamia' : 'companion',
'composie' : 'compost',
'composit' : 'compost',
'composote' : 'compost',
'compreshion' : 'compression',
'compresser' : 'compressor',
'compressro' : 'compressor',
'compsit' : 'compostt',
'compund' : 'compound',
'conc' : 'concrete',
'concerte' : 'concrete',
'concete' : 'concrete',
'concintrete' : 'concrete',
'concreate' : 'concrete',
'concreet' : 'concrete',
'concrere' : 'concrete',
'concretetile' : 'concrete tile',
'concrette' : 'concrete',
'concrte' : 'concrete',
'conctete' : 'concrete',
'condesate' : 'condensate',
'condiioner' : 'conditioner',
'condit' : 'conduit',
'conditioing' : 'conditioning',
'conditionar' : 'conditioner',
'conditioneer' : 'conditioner',
'conditioner/heater' : 'conditioner heater',
'conditionerriding' : 'conditioner',
'conditioners/heater' : 'conditioner',
'conditiooning' : 'conditioning',
'conditior' : 'condition',
'conditon' : 'condition',
'condiut' : 'conduit',
'condtioners' : 'conditioners',
'condtioning' : 'conditioning',
'conduet' : 'conduit',
'conduit,' : 'conduit',
'conector' : 'connector',
'conemporary' : 'contemporary',
'confrence' : 'conference',
'connecto' : 'connect',
'connectoer' : 'connector',
'connectorsa' : 'connectors',
'connectorv' : 'connector',
'connnector' : 'connector',
'conroller' : 'controller',
'constraction' : 'contraction',
'contaiers' : 'containers',
'containwes' : 'containments',
'contaner' : 'container',
'contempery' : 'contemporary',
'continers' : 'containers',
'continuos' : 'continuous',
'contl' : 'cont',
'contorl' : 'control',
'contracor' : 'contractor',
'contrcator' : 'contractor',
'contro' : 'control',
'controle' : 'control',
'controler' : 'controller',
'controlle' : 'controller',
'convction' : 'convection',
'convectionoven' : 'convection oven',
'converion' : 'conversion',
'coordless' : 'cordless',
'copact' : 'compact',
'coragated' : 'corrugated',
'coranado' : 'coronado',
'cord,' : 'cord',
'cordclass' : 'cord class',
'corded/cordless' : 'corded cordless',
'cordlees' : 'cordless',
'cordlessrotary' : 'cordless rotary',
'cordyellow' : 'cord yellow',
'corelais' : 'cordless',
'corner-' : 'corner',
'cornershower' : 'corner shower',
'cornewr' : 'corner',
'cornor' : 'corner',
'corragated' : 'corrugated',
'corroseal' : 'corrosive',
'corrougated' : 'corrugated',
'corrougeted' : 'corrugated',
'costum' : 'custom',
'cota' : 'coat',
'coth' : 'cot',
'coucg' : 'couch',
'couchen' : 'couches',
'couipling' : 'coupling',
'coulpler' : 'coupler',
'couner' : 'counter',
'counertop' : 'counter top',
'counterdepth' : 'counter depth',
'counterto' : 'counter top',
'countertop,' : 'counter top',
'couplingg' : 'coupling',
'courant' : 'corner',
'courner' : 'corner',
'covedrs' : 'covers',
'cover,' : 'cover',
'coversion' : 'conversion',
'covrs' : 'covers',
'cpipe' : 'pipe',
'craftig' : 'crafting',
'craftman' : 'craftsman',
'craftsm,an' : 'craftsman',
'crimpling' : 'crimping',
'crinp' : 'crisp',
'cros' : 'crews',
'crossties' : 'cross ties',
'crub' : 'curb',
'ctop' : 'top',
'ctrical' : 'electrical',
'cubeicals' : 'cubic',
'cubicel' : 'cubic',
'cucbi' : 'cubic',
'cuctis' : 'curtain',
'cuitain' : 'curtain',
'culligan' : 'mulligan',
'cuplings' : 'couplings',
'cuppling' : 'cupping',
'curlex' : 'curler',
'curtian' : 'curtain',
'curtiins' : 'curtains',
'curtin' : 'curtain',
'curtins' : 'curtains',
'curton' : 'curtain',
'cushiobs' : 'cushions',
'cushions/marth' : 'cushion',
'cusion' : 'cushion',
'cusions' : 'cushions',
'custo' : 'custom',
'cut-off' : 'cutoff',
'cut-out' : 'cutout',
'cut-to-size' : 'customize',
'cutain' : 'curtain',
'cutkler' : 'cutler',
'cutte' : 'cute',
'cutter/deburring' : 'cutter',
'cyculer' : 'cycler',
'cylinoid' : 'cylinder',
'cynlinder' : 'cylinder',
'cyprees' : 'cypreses',
'd,outdoor' : 'outdoorsy',
'dacor' : 'decor',
'dakato' : 'dakota',
'dampiner' : 'dampener',
'dampr' : 'damp',
'danby' : 'bandy',
'danze' : 'daze',
'dap' : 'pad',
'dappy' : 'sappy',
'dasco' : 'disco',
'daucets' : 'faucets',
'daylillies' : 'daylights',
'dcanvas' : 'canvas',
'ddeck' : 'deck',
'ddoors' : 'doors',
'ddor' : 'odor',
'ddummy' : 'dummy',
'de-ice' : 'deice',
'de-icing' : 'deicing',
'deadblow' : 'dead blow',
'deask' : 'desk',
'decke' : 'deck',
'decker,' : 'decker',
'deckerbattery' : 'decker battery',
'deckin' : 'decking',
'deckmate' : 'decimate',
'deckpaint' : 'deck paint',
'decoart' : 'deco art',
'decoator' : 'decorator',
'decocolor' : 'deco color',
'decora/gfci' : 'decorating',
'decoritive' : 'decorative',
'decostrip' : 'deco strip',
'decrotive' : 'decorative',
'dect' : 'sect',
'dectectors' : 'detectors',
'dector' : 'decor',
'dectot' : 'defector',
'dedector' : 'detector',
'dedwalt' : 'desalted',
'deecals' : 'decals',
'deer-resistant' : 'nonresistant',
'deerfield' : 'deer field',
'defence' : 'defense',
'dehimid' : 'dehumidifier',
'dehumidifyer' : 'dehumidifier',
'dek' : 'desk',
'delata' : 'delta',
'delfector' : 'deflector',
'delonghi' : 'sidelong',
'demin' : 'denim',
'deocorative' : 'decorative',
'deountable' : 'demountable',
'dep' : 'deep',
'depot.com/search=galvanized' : 'galvanized',
'depp' : 'deep',
'desighn' : 'design',
'desposal' : 'disposal',
'destin' : 'destine',
'detecter' : 'detector',
'detectors/carbon' : 'detector',
'deterent' : 'deterrent',
'dewall' : 'dewalt',
'dewalr' : 'dewalt',
'dewalt,' : 'dewalt',
'dewaqlt' : 'dewalt',
'dhower' : 'dower',
'diamondplate' : 'diamond plate',
'diat' : 'fiat',
'didger' : 'ridged',
'digz' : 'dig',
'diining' : 'dining',
'dimable' : 'disable',
'dimond' : 'diamond',
'dimplex' : 'dimple',
'disck' : 'disk',
'discon' : 'discontinued',
'discontinnued' : 'discontinued',
'discontinuedbrown' : 'discontinued brown',
'dishs' : 'dish',
'dishwaaher' : 'dishwasher',
'dishwaser' : 'dishwasher',
'disinfectent' : 'disinfectant',
'disonnect' : 'disconnect',
'dispencer' : 'dispenser',
'dispensor' : 'dispenser',
'distresed' : 'distressed',
'distributipn' : 'distribution',
'dit' : 'it',
'diverer' : 'diverge',
'diverte' : 'divert',
'divonshire' : 'devonshire',
'dleta' : 'delta',
'dlight' : 'light',
'dmi' : 'dim',
'dobble' : 'cobble',
'doooors' : 'door',
'dooor' : 'door',
'door,' : 'door',
'door-in-door' : 'door in door',
'door/divider' : 'door divider',
'doorbe;;' : 'doorbell',
'doorguard' : 'door guard',
'doorhinges' : 'door hinges',
'dooroil' : 'door oil',
'doorr' : 'door',
'doors,' : 'doors',
'doors:' : 'doors',
'doorser' : 'doorstep',
'doorsfold' : 'doors fold',
'doorsmoocher' : 'doors moocher',
'doorspring' : 'door spring',
'doorsscreen' : 'doors screen',
'doorsth' : 'door',
'doort' : 'door',
'doos' : 'door',
'dorr' : 'door',
'dorset' : 'closet',
'double;' : 'double',
'doublesided' : 'double sided',
'doubletowel' : 'double towel',
'doublew' : 'double',
'dracket' : 'bracket',
'draweer' : 'drawer',
'dril' : 'drill',
'drill/driver' : 'drill driver',
'drillimpact' : 'drill impact',
'drils' : 'drills',
'drione' : 'drone',
'dripper/e' : 'dripper',
'driveing' : 'driving',
'driverway' : 'driveway',
'drop-in' : 'dropping',
'dropcloth' : 'drop cloth',
'drower' : 'drawer',
'drp' : 'drip',
'drve' : 'drive',
'drw' : 'drawer',
'dry/wet' : 'dry wet',
'dryder' : 'dryer',
'drydex' : 'dryer',
'drye' : 'dryer',
'dryed' : 'dryer',
'dryer,' : 'dryer',
'drywal' : 'drywall',
'dstaples' : 'staples',
'dtop' : 'top',
'dule' : 'duel',
'durablack' : 'durable',
'duraflame' : 'durableness',
'duratemp' : 'duration',
'durawall' : 'duracell',
'dusk/dawn' : 'dusk dawn',
'dut' : 'duet',
'dutchlap' : 'dutch lap',
'dutty' : 'duty',
'dwall' : 'wall',
'dynamix' : 'dynamic',
'dyrer' : 'dryer',
'earthgro' : 'earth grow',
'earthgrow' : 'earth grow',
'earthquaike' : 'earthquake',
'eastbay' : 'east bay',
'easylight' : 'easy light',
'eathgrow' : 'earth grow',
'eatrhwise' : 'lengthwise',
'ectric' : 'electric',
'edgere' : 'edger',
'edget' : 'edge',
'edgetape' : 'edge tape',
'edginh' : 'edging',
'effeciency' : 'efficiency',
'egedg' : 'egged',
'eiectric' : 'electric',
'elbo' : 'elbow',
'elboq' : 'elbow',
'elctric' : 'electric',
'ele.c' : 'elect',
'elec.' : 'elect',
'elecetrity' : 'electricity',
'elecric' : 'electric',
'elecronic' : 'electronic',
'electical' : 'electrical',
'electically' : 'eclectically',
'electirc' : 'electric',
'electral' : 'electoral',
'electrcial' : 'electrical',
'electrian' : 'electrician',
'electrica' : 'electric',
'electrichot' : 'electric hot',
'electriv' : 'electric',
'electrtical' : 'electrical',
'electtric' : 'electric',
'elemnet' : 'element',
'elerical' : 'electric',
'eletric' : 'electric',
'elicreic' : 'electric',
'elictric' : 'electric',
'eliment' : 'aliment',
'elongagated' : 'elongated',
'elongaterd' : 'elongated',
'elrctric' : 'electric',
'eltron' : 'electron',
'emergancy' : 'emergency',
'emergensy' : 'emergency',
'empact' : 'impact',
'emparador' : 'paradoxic',
'emperial' : 'imperial',
'enamal' : 'enamel',
'enchors' : 'anchors',
'enclouseure' : 'enclosure',
'encosure' : 'enclosure',
'enduro' : 'endure',
'enfineered' : 'engineered',
'enrty' : 'entry',
'entension' : 'intension',
'entery' : 'entry',
'entrydoors' : 'entry doors',
'envirolite' : 'environment',
'epoxyshield' : 'epoxy shield',
'eppoxy' : 'epoxy',
'equitment' : 'equipment',
'eshaust' : 'exhaust',
'essencekitchen' : 'essence kitchen',
'esterior' : 'posterior',
'estore' : 'store',
'estwing' : 'stewing',
'ethjernet' : 'ethernet',
'eucalptus' : 'eucalyptus',
'eurothem' : 'europium',
'everbuilt' : 'overbuilt',
'exacto' : 'exact',
'exaust' : 'exhaust',
'excaust' : 'exhaust',
'excellartor' : 'excellent',
'exhaustless' : 'exhaust less',
'exhust' : 'exhaust',
'exide' : 'oxide',
'expand-it' : 'expandability',
'expanion' : 'expansion',
'expoxy' : 'epoxy',
'expsnsion' : 'expansion',
'exstension' : 'extension',
'exstention' : 'distention',
'extenion' : 'extension',
'extenison' : 'extension',
'extensoion' : 'extension',
'exteria' : 'exterior',
'exterier' : 'exterior',
'exterieur' : 'exterior',
'exteriordoors' : 'exterior doors',
'exteriorpaint' : 'exterior paint',
'exteriro' : 'exterior',
'externol' : 'external',
'extertal' : 'external',
'extinguishhers' : 'extinguishers',
'extior' : 'exterior',
'extirior' : 'exterior',
'extorior' : 'exterior',
'extrior' : 'exterior',
'fabn' : 'fan',
'fabreeze' : 'fa breeze',
'fabris' : 'fabrics',
'fairfield,' : 'fairfield',
'falcet' : 'facet',
'fameless' : 'frameless',
'fan,' : 'fan',
'fan,low' : 'fan low',
'fan-powered' : 'fan powered',
'fan/light' : 'fan light',
'fanall' : 'fan all',
'fanc' : 'fan',
'fane' : 'fan',
'fanlite' : 'fan lite',
'fantdoors' : 'door',
'fantsastic' : 'fantastic',
'fasad' : 'farad',
'fasade' : 'facade',
'fatpack' : 'fat pack',
'faucethandle' : 'faucet handle',
'faucets-' : 'faucets',
'faucets/risers' : 'faucets risers',
'faucetskitchen' : 'faucets kitchen',
'faucett' : 'faucet',
'fauchet' : 'faucet',
'faucit' : 'faucet',
'fauctes' : 'faucets',
'faucwts' : 'faucets',
'fauet' : 'faucet',
'faul' : 'fault',
'fauset' : 'faucet',
'fawcet' : 'facet',
'feeed' : 'feed',
'feerzer' : 'freezer',
'feiss' : 'fess',
'feit' : 'fat',
'felx' : 'flex',
'femaie' : 'female',
'femle' : 'female',
'fencde' : 'fenced',
'fenceing' : 'fencing',
'fenching' : 'fencing',
'fenving' : 'fencing',
'fermaldehyde' : 'formaldehyde',
'fernace' : 'furnace',
'fernco' : 'fern co',
'ferroker' : 'ferrous',
'ferroue' : 'ferrous',
'fertilizer,' : 'fertilizer',
'fertillzer' : 'fertilizer',
'ffill' : 'fill',
'fictures' : 'pictures',
'fiepits' : 'fire pits',
'filerts' : 'filers',
'filters,' : 'filters',
'filtes' : 'files',
'filtm' : 'film',
'filtrete' : 'filtrate',
'findeer' : 'finder',
'fine/line' : 'fine line',
'finethread' : 'fine thread',
'finish-wood' : 'finish wood',
'fip' : 'flip',
'firecaly' : 'firecracker',
'fireless' : 'fire less',
'firepace' : 'fire place',
'fireplacewater' : 'fire place water',
'firepot' : 'fire pot',
'firetreat' : 'fire treat',
'firlters' : 'filters',
'fittin' : 'fitting',
'fitting,' : 'fitting',
'fittings,' : 'fittings',
'fixtres' : 'fixtures',
'fixtues' : 'fixtures',
'fixtures,' : 'fixtures',
'fixures' : 'fixtures',
'flagmakers' : 'flag makers',
'flanges/holders' : 'slaveholders',
'flasheing' : 'flashing',
'flashingm' : 'flashing',
'flashlightts' : 'flashlights',
'flashning' : 'flashing',
'flat-head' : 'flathead',
'flatbraces' : 'flat braces',
'flexable' : 'flexible',
'flexiblr' : 'flexible',
'flexlock' : 'flex lock',
'flexogen' : 'exogenous',
'flexwrap' : 'flex wrap',
'flexzilla' : 'flexibility',
'flim' : 'film',
'flixible' : 'flexible',
'fllor' : 'floor',
'fllors' : 'floors',
'fllters' : 'filters',
'floaties' : 'floater',
'floatinf' : 'floating',
'floodlight,' : 'floodlight',
'floorcleaners' : 'floor cleaners',
'flooring,' : 'flooring',
'floorinh' : 'flooring',
'floorong' : 'flooring',
'floorring' : 'flooring',
'floot' : 'floor',
'florcant' : 'Fluorescent ',
'florecent' : 'Fluorescent ',
'florencet' : 'Fluorescent ',
'florent' : 'Fluorescent ',
'florenteen' : 'Fluorescent ',
'floresant' : 'Fluorescent ',
'florient' : 'Fluorescent ',
'floring' : 'flooring',
'florisant' : 'Fluorescent ',
'florring' : 'flooring',
'flors' : 'floors',
'florsent' : 'Fluorescent ',
'floting' : 'floating',
'flourecent' : 'Fluorescent ',
'flourscent' : 'Fluorescent ',
'flpwers' : 'flowers',
'fluoreecent' : 'fluorescent',
'fluorescant' : 'fluorescent',
'fluorscent' : 'fluorescent',
'flurecent' : 'Fluorescent ',
'flurescent' : 'fluorescent',
'flurniture' : 'furniture',
'flurorescent' : 'fluorescent',
'flushmate' : 'flush mate',
'foamular' : 'formula',
'foldin' : 'folding',
'folfable' : 'fold table',
'foof' : 'roof',
'footaluminum' : 'foot aluminum',
'forecasteer' : 'forecaster',
'forgednails' : 'forged nails',
'forimca' : 'formica',
'fosets' : 'closets',
'fotage' : 'footage',
'foundstion' : 'foundation',
'fountin' : 'fountain',
'fraiming' : 'framing',
'fraiser' : 'raiser',
'fram' : 'frame',
'framelessmirror' : 'frameless mirror',
'framin' : 'framing',
'framless' : 'frameless',
'frazee' : 'frazer',
'freesstanding' : 'free standing',
'freezer,' : 'freezer',
'freezerz' : 'freezer',
'frenchdoor' : 'french door',
'freplace' : 'replace',
'frezer' : 'freezer',
'fridaire' : 'refrigerator',
'fridgdare' : 'fridge',
'fridgedaire' : 'refrigerator',
'fridgidaire' : 'refrigerator',
'fridgidare' : 'refrigerator',
'fridigdaire' : 'refrigerator',
'fridigidaire' : 'refrigerator',
'frigadaire' : 'refrigerator',
'frigde' : 'fridge',
'frigerator' : 'refrigerator',
'frigidair' : 'fridge',
'frigidare' : 'fridge',
'frnch' : 'fridge',
'frontload' : 'front load',
'frrezer' : 'freezer',
'ftames' : 'frame',
'fuacet' : 'faucet',
'fuelpellets' : 'fuel pellets',
'fuil' : 'fuel',
'fulters' : 'filters',
'fungacide' : 'fungicide',
'furiture' : 'furniture',
'furnance' : 'furnace',
'furnature' : 'furniture',
'fushion' : 'fusion',
'g/lf' : 'golf',
'gagarage' : 'garage',
'gaint' : 'giant',
'galllon' : 'gallon',
'gallondrywall' : 'gallon drywall',
'galloon' : 'gallon',
'galv' : 'gal',
'galvanaized' : 'galvanized',
'galvanise' : 'galvanize',
'galvanised' : 'galvanized',
'galvanisedround' : 'galvanized round',
'galvenized' : 'galvanized',
'galvinezed' : 'galvanized',
'galvinize' : 'galvanize',
'galvinized' : 'galvanized',
'gaperaser' : 'gap eraser',
'gaqs' : 'gas',
'garag' : 'garage',
'garage,' : 'garage',
'garagedoor' : 'garage door',
'gardden' : 'garden',
'gardena' : 'garden',
'gardenn' : 'garden',
'gardinias' : 'gardenias',
'gardn' : 'grand',
'gargage' : 'garage',
'garlend' : 'garden',
'garvanized' : 'galvanized',
'gasnstove' : 'gastronome',
'gasolene' : 'gasoline',
'gasquet' : 'gasket',
'gaurds' : 'guards',
'gavanized' : 'galvanized',
'gearwrench' : 'gear wrench',
'genecrac' : 'generate',
'generaor' : 'generator',
'generater' : 'generate',
'generaters' : 'generates',
'ginder' : 'grinder',
'glaciar' : 'glacier',
'glacie' : 'glacier',
'glenwood' : 'glen wood',
'glu' : 'glue',
'gluetm' : 'gluer',
'govenore' : 'governor',
'grage' : 'garage',
'grainte' : 'granite',
'grandview' : 'grand view',
'granit' : 'grant',
'granitecounter' : 'granite counter',
'granitne' : 'granite',
'granuels' : 'granules',
'grasa' : 'grass',
'grat' : 'rat',
'gratewhite' : 'grate white',
'greak' : 'greek',
'grease,' : 'grease',
'greaseless' : 'grease less',
'gree' : 'gee',
'greecianmarble' : 'greenmail',
'greem' : 'grim',
'greenh' : 'green',
'gridle' : 'girdle',
'gril' : 'grill',
'grills-gas' : 'grill gas',
'grils' : 'grill',
'groud' : 'ground',
'groung' : 'ground',
'grqss' : 'grass',
'gte' : 'get',
'gtxworks' : 'waxworks',
'guarf' : 'guard',
'guarge' : 'guarded',
'guarter' : 'garter',
'gugs' : 'rugs',
'gurad' : 'guard',
'gutter,' : 'gutter',
'gutter/' : 'gutter',
'gwtters' : 'gutter',
'haalogen' : 'halogen',
'habachi' : 'hibachi',
'habor' : 'harbor',
'hacr' : 'char',
'hadwre' : 'hardwire',
'hagchet' : 'hatchet',
'haging' : 'aging',
'haier' : 'hair',
'hainsaw' : 'chainsaw',
'hallogen' : 'halogen',
'hammerss' : 'hammers',
'hampden' : 'hampton',
'hamptom' : 'hampton',
'handel' : 'handle',
'handels' : 'handles',
'handi' : 'hand',
'handical' : 'handicap',
'handle,' : 'handle',
'handtools' : 'hand tools',
'handycap' : 'handicap',
'hansgroph' : 'hansgrohe',
'haolgen' : 'halogen',
'harbour' : 'harbor',
'hardi' : 'hard',
'hardiboard' : 'hardboard',
'hardiepanel' : 'hardiness',
'hardner' : 'harden',
'hardsware' : 'hardware',
'hardw' : 'hard',
'hardwar' : 'hardware',
'hardware,' : 'hardware',
'hardwawrd' : 'hardware',
'hardwoo' : 'hardwood',
'harware' : 'hardware',
'hasmilton' : 'hamilton',
'hasmmock' : 'hammock',
'hattic' : 'attic',
'hausys' : 'hauser',
'havc' : 'havoc',
'haven,' : 'haven',
'hawian' : 'hawaiian',
'headboaed' : 'headboard',
'headger' : 'hedger',
'headlok' : 'headlock',
'heat/ac' : 'heat air condition',
'heater\'' : 'heater',
'heatere' : 'heater',
'heatgasget' : 'heat',
'heatr' : 'heart',
'heatres' : 'heaters',
'heavy-duty' : 'heavy duty',
'heavyduty' : 'heavy duty',
'heculine' : 'masculine',
'hecurles' : 'hercules',
'heters' : 'heaters',
'hexgon' : 'hexagon',
'hexpin' : 'hex pin',
'hhigh' : 'high',
'hibascus' : 'hibiscus',
'hickorya' : 'hickory',
'hidraulic' : 'hydraulic',
'hieght' : 'height',
'high-efficiency' : 'efficiency',
'high-efficiency,' : 'efficiency',
'hightop' : 'high top',
'himalya' : 'himalaya',
'hindge' : 'hinge',
'hindged' : 'hinged',
'hindges' : 'hinges',
'hinged,' : 'hinged',
'hinghs' : 'hinge',
'hoisst' : 'hoists',
'holegen' : 'hole gen',
'homelight' : 'home light',
'homes,' : 'homes',
'homeywell' : 'honeywell',
'honewell' : 'honeywell',
'horizantel' : 'horizontal',
'hot/cold' : 'hot cold',
'hottube' : 'hot tube',
'hottubs' : 'hot tubs',
'hotwater' : 'hot water',
'hoursepower' : 'horsepower',
'hprse' : 'horse',
'hummngbird' : 'hummingbird',
'huntshire' : 'hunt shire',
'huricane' : 'hurricane',
'hurracaine' : 'hurricane',
'huskey' : 'husky',
'huskie' : 'huskies',
'huskt' : 'husk',
'hvlp' : 'help',
'hydrolic' : 'hydraulic',
'hydrophonics' : 'hydroponics',
'hyrdaulic' : 'hydraulic',
'icey' : 'icy',
'iches' : 'inch',
'icnh' : 'inch',
'iiluminart' : 'illuminate',
'illusione' : 'illusion',
'ilumination' : 'illumination',
'impellor' : 'impeller',
'in.white' : 'white',
'inanchor' : 'in anchor',
'incandecent' : 'incandescent',
'ince' : 'nice',
'inces' : 'inch',
'inch\'' : 'inch',
'inche' : 'inch',
'inchesbathroom' : 'inches bathroom',
'inchtrack' : 'inch track',
'inchvinyl' : 'inch vinyl',
'incide' : 'inside',
'incn' : 'inch',
'incounter' : 'encounter',
'incresers' : 'increaser',
'incyh' : 'inch',
'indoor/otdoor' : 'indoor outdoor',
'indoor/outdoor' : 'indoor outdoor',
'industreial' : 'industrial',
'inerior' : 'interior',
'inetrior' : 'interior',
'infered' : 'inferred',
'inferni' : 'inferno',
'inflex' : 'influx',
'infloor' : 'in floor',
'infred' : 'infrared',
'ingniter' : 'igniter',
'inovations' : 'innovations',
'insallation' : 'installation',
'insaller' : 'installer',
'insh' : 'inch',
'insided' : 'inside',
'insinkerator' : 'insinuator',
'insol' : 'insole',
'insolated' : 'isolated',
'insructions' : 'instructions',
'instahanger' : 'interchanger',
'instalation' : 'installation',
'instasmart' : 'installment',
'instock' : 'in stock',
'instulation' : 'insulation',
'insualation' : 'insulation',
'insulaation' : 'insulation',
'insulaion' : 'insulation',
'insulatino' : 'insulation',
'insulatiom' : 'insulation',
'insulation\'' : 'insulation',
'insullation' : 'insulation',
'insurts' : 'inserts',
'intercomm' : 'intercom',
'interdesign' : 'inter design',
'interior/exterior' : 'interior',
'interiorwith' : 'interior with',
'interloclk' : 'interlock',
'interor' : 'interior',
'intersate' : 'interstate',
'intertape' : 'inter tape',
'invertor' : 'inverter',
'inxh' : 'inch',
'ironboard' : 'iron board',
'irorn' : 'iron',
'irragation' : 'irrigation',
'islating' : 'slating',
'isunderlayment' : 'is under layment',
'itght' : 'tight',
'itier' : 'tier',
'itwinkle' : 'twinkle',
'iuron' : 'iron',
'japenes' : 'japanese',
'jefrrey' : 'jeffrey',
'jhardware' : 'hardware',
'jigsaww' : 'jigsaw',
'jimmyproof' : 'jimmy proof',
'jirdon' : 'jordon',
'jmestown' : 'jamestown',
'jnches' : 'inches',
'jogsaw' : 'jigsaw',
'joing' : 'join',
'joinst' : 'joints',
'joisthangers' : 'joist hangers',
'jublilee' : 'jubilee',
'juera' : 'juicer',
'kage' : 'cage',
'kelloggs' : 'kellogg',
'kendalwood' : 'sandalwood',
'keorsene' : 'kerosene',
'kerosine' : 'kerosene',
'keurig' : 'keyring',
'keydoor' : 'key door',
'keys,' : 'keys',
'keystock' : 'key stock',
'kichen' : 'kitchen',
'kidcraft' : 'kid craft',
'kidie' : 'kiddie',
'kihchen' : 'kitchen',
'killerique' : 'killer',
'killers/electronic' : 'killers electronic',
'kintchen' : 'kitchen',
'kist' : 'kits',
'kit/right' : 'kit right',
'kitch' : 'kitchen',
'kitcheen' : 'kitchen',
'kitchenaid' : 'kitchenaid',
'kitchenaide' : 'kitchenaid',
'kitchenfaucet' : 'kitchen faucet',
'kitchenmaid' : 'kitchenaid',
'kitchenover' : 'kitchen over',
'kithchen' : 'kitchen',
'kithen' : 'kitchen',
'kkitchen' : 'kitchen',
'kkohler' : 'kohler',
'knicken' : 'knicker',
'knobreplacement' : 'knob replacement',
'knobsd' : 'knobs',
'knobsw' : 'knobs',
'knobw' : 'knobs',
'knops' : 'knobs',
'knoty' : 'knot',
'kobalt' : 'cobalt',
'koehler' : 'kohler',
'kohler,' : 'kohler',
'kohlerdrop' : 'kohler drop',
'kohlor' : 'kohler',
'koler' : 'kohler',
'kolher' : 'kohler',
'kombo' : 'combo',
'kphler' : 'kohler',
'kraftmaid' : 'kraft maid',
'kraftsman' : 'craftsman',
'kraus' : 'krause',
'krylon' : 'krypton',
'ktoilet' : 'toilet',
'kwiksest' : 'clockwise',
'laddert' : 'ladder',
'lader' : 'ladder',
'lakeshore' : 'lake shore',
'laminet' : 'laminate',
'laminite' : 'laminate',
'laminte' : 'laminate',
'lampost' : 'lamp post',
'lampsade' : 'lamp shade',
'lanco' : 'lance',
'landscasping' : 'landscaping',
'lanscape' : 'landscape',
'lanterun' : 'lantern',
'lanyard,' : 'lanyard',
'latchbolt' : 'latch bolt',
'latice' : 'lattice',
'latters' : 'lattes',
'lattiace' : 'lattice',
'lavitory' : 'lavatory',
'lawm' : 'lawn',
'lawndry' : 'laundry',
'lawnscarpenter' : 'lawns carpenter',
'layaway?' : 'lay away',
'layndry' : 'laundry',
'lbathroom' : 'bathroom',
'lcoks' : 'locks',
'leadders' : 'ladders',
'leafgrow' : 'leaf grow',
'lectric' : 'electric',
'ledbulb' : 'led bulb',
'leds' : 'led',
'leminate' : 'laminate',
'lettters' : 'letters',
'leum' : 'ileum',
'levelquick' : 'level quick',
'leverlock' : 'lever lock',
'levin' : 'liven',
'levinton' : 'levine',
'lgue' : 'glue',
'lifeproof' : 'life proof',
'liftmaster' : 'lift master',
'ligghts' : 'lights',
'lighs' : 'lights',
'light-' : 'light',
'light/' : 'light',
'lightbulb' : 'light bulb',
'lightin' : 'lighting',
'lightjs' : 'lights',
'lights/bronze' : 'lights bronze',
'lightsavannah' : 'light savannah',
'lightsensor' : 'light sensor',
'lightwall' : 'light wall',
'ligt' : 'light',
'ligtening' : 'lightening',
'ligthining' : 'lightening',
'ligths' : 'lights',
'ligts' : 'light',
'liht' : 'light',
'liminate' : 'luminate',
'linden,' : 'linden',
'line,' : 'line',
'lines,' : 'lines',
'linesplice' : 'line splice',
'linnart' : 'linnaeus',
'linzer' : 'liner',
'lioghting' : 'lighting',
'liqwuid' : 'liquid',
'litex' : 'lite',
'lithium-ion' : 'lithium',
'lithonia' : 'lithograph',
'lithum' : 'lithium',
'lituim' : 'lithium',
'lmainate' : 'laminate',
'lnsulated' : 'insulated',
'loadspeaker' : 'loudspeaker',
'locationlight' : 'location light',
'locite' : 'locate',
'lockin' : 'locking',
'locknut,' : 'locknut',
'lockout/tagout' : 'lockout',
'locktite' : 'lockstep',
'louvored' : 'louvered',
'lowvoltage' : 'low voltage',
'lquid' : 'quid',
'lshower' : 'shower',
'lspacers' : 'spacers',
'luever' : 'lever',
'maglite' : 'mag lite',
'magnectic' : 'magnetic',
'magniflier' : 'magnifier',
'mahoghany' : 'mahogany',
'maiid' : 'maid',
'mainfold' : 'manifold',
'maintance' : 'maintenance',
'maker,repair' : 'repairman',
'makersbot' : 'makers bot',
'malbu' : 'album',
'mandoors' : 'man doors',
'manganetic' : 'magnetic',
'mansonry' : 'masonry',
'maogani' : 'mahogany',
'maouse' : 'mouse',
'mapp' : 'map',
'marbel' : 'marble',
'marbl;e' : 'marble',
'marble/granite/en' : 'marble granite',
'marey' : 'mable',
'marineweld' : 'marine weld',
'marithon' : 'marathon',
'mashine' : 'machine',
'masterbuilt' : 'master built',
'mastercool' : 'master cool',
'masterlock' : 'master lock',
'masterpeice' : 'masterpiece',
'mataeials' : 'materials',
'material,' : 'material',
'maxfire' : 'max fire',
'maxima' : 'maxim',
'maxxair' : 'maximizer',
'maytab' : 'may tab',
'maytag' : 'may tag',
'mcmaster' : 'masterly',
'mconnection' : 'connection',
'mdfrosette' : 'rosette',
'mean?' : 'mean',
'measure:' : 'measure',
'meatal' : 'metal',
'mechanis' : 'mechanics',
'medalion' : 'medallion',
'medalions' : 'medallions',
'medallians' : 'medallions',
'medecine' : 'medicine',
'medialons' : 'medallions',
'mediumpond' : 'medium pond',
'megashot' : 'mega shot',
'melimine' : 'melamine',
'melmane' : 'melamine',
'melomine' : 'melamine',
'membrame' : 'membrane',
'mesquito' : 'mosquito',
'metal/' : 'metal',
'metaliks' : 'metalized',
'metallicpaint' : 'metallic paint',
'metl' : 'melt',
'metris' : 'metrics',
'mettal' : 'metal',
'mial' : 'mail',
'micewave' : 'microwave',
'microwarve' : 'microwave',
'midea' : 'media',
'milimet' : 'millimeter',
'milstead' : 'mil stead',
'miluakee' : 'milwaukee',
'milwakee' : 'milwaukee',
'milwalke' : 'milwaukee',
'milwankee' : 'milwaukee',
'milwaukie' : 'milwaukee',
'milwaulkee' : 'milwaukee',
'milwoki' : 'milwaukee',
'milwuakee' : 'milwaukee',
'minimate' : 'mini mate',
'miniture' : 'miniature',
'minka' : 'mink',
'mircowave' : 'microwave',
'miror' : 'mirror',
'mirrior' : 'mirror',
'mirrir' : 'mirror',
'mirro' : 'mirror',
'mirroes' : 'mirror',
'mirror,' : 'mirror',
'mirros' : 'morris',
'mirrow' : 'mirror',
'misquito' : 'mosquito',
'mistos' : 'mists',
'mitte' : 'mite',
'mitter' : 'miter',
'mivrowave' : 'microwave',
'mixet' : 'mixes',
'mmirror' : 'mirror',
'mmodel' : 'model',
'mobilehome' : 'mobile home',
'mobilhomes' : 'mobilizes',
'model:' : 'model',
'module.module' : 'module',
'mohogany' : 'mahogany',
'moiunting' : 'mounting',
'moldinf' : 'molding',
'molemax' : 'mole max',
'mollybold' : 'molly bold',
'momeni' : 'moment',
'monotor' : 'monitor',
'monoxcide' : 'monoxide',
'mosaik' : 'mosaic',
'mosia' : 'mosaic',
'mosiac' : 'mosaic',
'mosiacs' : 'mosaics',
'motionsense' : 'motion sense',
'mounteddrop' : 'mounted drop',
'mountreading' : 'mount reading',
'mowe' : 'mower',
'mower,' : 'mower',
'mower-' : 'mower',
'mowerectrical' : 'mower elctrical',
'mowre' : 'mower',
'mozaic' : 'mosaic',
'mp-t' : 'mph',
'mpr' : 'mph',
'mr.clean' : 'mr. clean',
'msaic' : 'mosaic',
'muliti' : 'multi',
'multi-colored' : 'multi colored',
'multi-location' : 'muti location',
'multi-outlet' : 'multi outlet',
'multi-position' : 'multi position',
'multi-purpose' : 'multi purpose',
'multi-tool' : 'multi tool',
'multinozzle' : 'multi nozzle',
'multipanel' : 'multi panel',
'multitool' : 'multi tool',
'm~ultralight' : 'ultralight',
'nai' : 'nail',
'nailes' : 'nails',
'nailgun' : 'nail gun',
'nailor' : 'nail',
'nailshand' : 'nails hand',
'nals' : 'nails',
'natur' : 'nature',
'naturaltone' : 'natural tone',
'naturlas' : 'naturals',
'needel' : 'needle',
'negitave' : 'negative',
'neiko' : 'seiko',
'netting,' : 'netting',
'neumatic' : 'nematic',
'neverkink' : 'never kink',
'newage' : 'sewage',
'newll' : 'null',
'nich' : 'inch',
'nickelshower' : 'nickel shower',
'nightlock' : 'night lock',
'non-insulated' : 'insulated',
'non-mortison' : 'cortisone',
'non-skid' : 'nonskid',
'noncontact' : 'non contact',
'nozle' : 'nozzle',
'nozzel' : 'nozzle',
'nozzzle' : 'nozzle',
'ntique' : 'antique',
'nutmag' : 'nutmeg',
'nuts/' : 'nuts',
'nylin' : 'nylon',
'oaint' : 'saint',
'oakmoss' : 'oak moss',
'oask' : 'oaks',
'oatu' : 'oat',
'ocket' : 'socket',
'ocuntry' : 'country',
'oden' : 'done',
'oerate' : 'orate',
'ofal' : 'foal',
'oganizers' : 'orgainzer',
'oil-rubbed' : 'oil rubbed',
'oilrubbed' : 'oil rubbed',
'olastic' : 'elastic',
'oleam' : 'gleam',
'oli' : 'oil',
'omnifilter' : 'omni filter',
'only?' : 'only',
'ontrol' : 'control',
'oolers' : 'toolers',
'openner' : 'opener',
'operataed' : 'operated',
'opererated' : 'operated',
'oppeuss' : 'oppress',
'orack' : 'rack',
'orange,' : 'orange',
'orchred' : 'orchard',
'oreck' : 'wreck',
'orgainzer' : 'organizer',
'organiser' : 'organizer',
'organiz' : 'organize',
'organozers' : 'organizers',
'orginizer' : 'organizer',
'orgnize' : 'organize',
'orian' : 'o ring',
'oride' : 'o ring',
'oring' : 'o ring',
'ornge' : 'o ting',
'osciallating' : 'oscillating',
'oscilating' : 'oscillating',
'oscilliating' : 'oscillating',
'otdoor' : 'outdoor',
'othor' : 'other',
'oulets' : 'outlets',
'ourdoor' : 'outdoor',
'ousite' : 'onsite',
'outdo?' : 'outdo',
'outdooor' : 'outdoor',
'outdoord' : 'outdoor',
'outdoorfurniture' : 'outdoor furniture',
'outdoorlounge' : 'outdoor lounge',
'outdoorstorage' : 'outdoor storage',
'outdors' : 'outdoors',
'outide' : 'outside',
'outler' : 'outer',
'outoddor' : 'outdoor',
'outodoor' : 'outdoor',
'outpoor' : 'outdoor',
'outsde' : 'outside',
'outsid' : 'outside',
'oven/combo' : 'oven combo',
'ovens;' : 'ovens',
'over-range' : 'over range',
'p-lant' : 'plant',
'paatio' : 'patio',
'padio' : 'patio',
'padspads' : 'pads pads',
'padtio' : 'patio',
'painnt' : 'paint',
'painr' : 'paint',
'paint,' : 'paint',
'paint/safire/satin' : 'paint safire satin',
'paintr' : 'paint',
'pan,' : 'pan',
'panelling' : 'paneling',
'panle' : 'panel',
'panles' : 'panels',
'pannel' : 'panel',
'papertowels' : 'paper towels',
'papper' : 'paper',
'paridise' : 'paradise',
'parkle' : 'sparkle',
'parkview' : 'park view',
'parkwood' : 'park wood',
'parnel' : 'panel',
'parque' : 'parquet',
'parquee' : 'parquet',
'partical' : 'partial',
'pastic' : 'plastic',
'patio/garden' : 'patio garden',
'patio/white' : 'patio white',
'pation' : 'patio',
'patioo' : 'patio',
'patr' : 'part',
'patternn' : 'pattern',
'paulista' : 'paulita',
'pavers:' : 'paver',
'pavestone' : 'pave stone',
'pebbble' : 'pebble',
'pecs' : 'specs',
'pedastal' : 'pedestal',
'pedelal' : 'pedestal',
'pedestial' : 'pedestal',
'pedistal' : 'pedestal',
'peelets' : 'pellets',
'pellats' : 'pallets',
'pellitized' : 'palletized',
'pendastal' : 'pendant',
'pendendant' : 'pendant',
'pendqnt' : 'pendent',
'perferated' : 'perforated',
'performa' : 'perform',
'perhung' : 'per hung',
'perscription' : 'prescription',
'persianas' : 'persians',
'petscreen' : 'pet screen',
'phillits' : 'phillips',
'phlne' : 'phone',
'picinic' : 'picnic',
'picketts' : 'pickets',
'piecs' : 'pieces',
'pilers,needlenose' : 'needlenose pilers',
'pinacle' : 'pinnacle',
'pipeinless' : 'pipelines',
'pipeinsulation' : 'pipe insulation',
'pipeized' : 'pipetted',
'pipies' : 'pipes',
'pivotangle' : 'pivot angle',
'planel' : 'panel',
'plankj' : 'plank',
'plannter' : 'planter',
'plaqstic' : 'plastic',
'plasic' : 'plastic',
'plasmawave' : 'plasma wave',
'plastic,' : 'plastic',
'plasticbathroom' : 'plastic bathroom',
'plastis' : 'plastics',
'plastix' : 'plastic',
'plates,' : 'plates',
'pleirs' : 'pliers',
'plna' : 'plan',
'plummbing' : 'plumbing',
'plygem' : 'ply gem',
'plymoth' : 'ply moth',
'plyweood' : 'plywood',
'pnematic' : 'pneumatic',
'pneumaitic' : 'pneumatic',
'pnumatic' : 'pneumatic',
'pocelain' : 'porcelain',
'poerated' : 'operated',
'poision' : 'poison',
'polesaw' : 'pole saw',
'policarbonate' : 'polycarbonate',
'polishewr' : 'polisher',
'polurethane' : 'polyurethane',
'polycarbonite' : 'polycarbonate',
'polyethylne' : 'polyethylene',
'polyeurethane' : 'polyurethane',
'polyurathane' : 'polyurethane',
'ponuds' : 'pounds',
'pooron' : 'poor on',
'porach' : 'poach',
'porble' : 'portable',
'porcalain' : 'porcelain',
'porcelaine' : 'porcelain',
'porceleain' : 'porcelain',
'porcelein' : 'porcelain',
'porcelian' : 'porcelain',
'porcelin' : 'porcelain',
'porceline' : 'porcelain',
'portabe' : 'portable',
'portabel' : 'portable',
'portcable' : 'portable',
'portercable' : 'porter cable',
'post,' : 'post',
'postlantern' : 'post lantern',
'poulty' : 'poultry',
'powerd' : 'powered',
'powere' : 'powered',
'powermark' : 'power mark',
'powermate' : 'power mate',
'powermax' : 'power max',
'powershop' : 'power shop',
'powertool' : 'power tool',
'powervent' : 'power vent',
'powrcoat' : 'powder bcat',
'poyurethane' : 'polyurethane',
'ppanel' : 'panel',
'pre-cut' : 'pre cut',
'pre-emergent' : 'pre emergent',
'pre-filter' : 'pre filter',
'pre-hung' : 'pre hung',
'pre-lit' : 'pre lit',
'pre-painted' : 'pre printed',
'preformance' : 'performance',
'preserva' : 'preserve',
'pressue' : 'pressure',
'pressuer' : 'pressure',
'pressure-balancing' : 'pressure balancing',
'pressure-treated' : 'pressure treated',
'presure' : 'pressure',
'presusre' : 'pressure',
'procelian' : 'porcelain',
'processer' : 'processor',
'produucts' : 'products',
'proflex' : 'pro flex',
'progect' : 'protect',
'proipane' : 'propane',
'proluxe' : 'pro luxe',
'protctor' : 'protector',
'protecter' : 'protector',
'protectionm' : 'protection',
'prpane' : 'propane',
'prppane' : 'propane',
'psint' : 'paint',
'ptouch' : 'touch',
'pullbehind' : 'pull behind',
'pulliepaarts' : 'pulley parts',
'pully' : 'pulley',
'pump,' : 'pump',
'punp' : 'pump',
'purell' : 'pulley',
'putifiers' : 'purifiers',
'pvc/composite' : 'pvc composite',
'pvc/cpvc' : 'pvc cpvc',
'pvcp' : 'pvc',
'pvcsch' : 'pvc',
'pywood' : 'plywood',
'qstatic' : 'static',
'qucikie' : 'quickie',
'quide' : 'guide',
'qwhite' : 'white',
'r;ubber' : 'rubber',
'racheting' : 'ratcheting',
'radiatior' : 'radiator',
'raido' : 'radio',
'raidos' : 'radios',
'railin' : 'railing',
'rainbarrel' : 'rain barrel',
'ramp,' : 'ramp',
'range/stove' : 'range stove',
'ranshower' : 'rain shower',
'ratator' : 'rotator',
'raymore' : 'ray more',
'rayobi' : 'ray obi',
'rayoby' : 'rayon',
'rayovac' : 'rayon',
'rbber' : 'rubber',
'reapair' : 'repair',
'recepicating' : 'replicating',
'recesse' : 'recess',
'recharable' : 'rechargeable',
'rechargale' : 'rechargeable',
'recipricating' : 'reciprocating',
'recirculator' : 'recirculation',
'recirculitating' : 'recirculating',
'recressed' : 'recessed',
'rectangele' : 'rectangle',
'rectangl' : 'rectangle',
'rectangulat' : 'rectangular',
'reease' : 'release',
'reffridge' : 'refrigerator',
'refigrator' : 'refrigerator',
'refil' : 'refill',
'refrdgerators' : 'refrigerator',
'refregirator' : 'refrigerator',
'refreidgerator' : 'refrigerator',
'refridegrator' : 'refrigerator',
'refriderator' : 'refrigerator',
'refridgerator' : 'refrigerator',
'refridgidere' : 'refrigerated',
'refrierator' : 'refrigerator',
'refrig' : 'refrigerator',
'refrig.' : 'refrigerator',
'refrigator' : 'refrigerator',
'refrigerater' : 'refrigerator',
'refrigerato' : 'refrigerator',
'refrigerator,' : 'refrigerator',
'refrigerator/wine' : 'refrigerator',
'refrigeratorators' : 'refrigerator',
'refrigeratore' : 'refrigerator',
'refrigeratot' : 'refrigerator',
'refrigeratr' : 'refrigerator',
'refrigertor' : 'refrigerator',
'refrigirator' : 'refrigerator',
'refrigrator' : 'refrigerator',
'regrigerators' : 'refrigerator',
'rehargeable' : 'rechargeable',
'reheem' : 'redeem',
'rejuviati' : 'rejuvenate',
'reliabilt' : 'reliability',
'remmnant' : 'remnant',
'remodal' : 'removal',
'renassaince' : 'renaissance',
'repacement' : 'replacement',
'repalcement' : 'replacement',
'repare' : 'repair',
'repir' : 'repair',
'replacemet' : 'replacement',
'replacemetn' : 'replacement',
'replacemtn' : 'replacement',
'replaclacemt' : 'replacement',
'requiered' : 'required',
'rerefrigerator' : 'refrigerator',
'residentialsteel' : 'residential steel',
'resitance' : 'resistance',
'restaint' : 'restraint',
'restistant' : 'resistant',
'reswood' : 'redwood',
'retaing' : 'retain',
'retiner' : 'retainer',
'rhandle' : 'handle',
'ridget' : 'ridge',
'ridiing' : 'riding',
'ridinng' : 'riding',
'right-hand' : 'right hand',
'right-step' : 'right step',
'rightheight' : 'right height',
'rite-temp' : 'rite temp',
'riverby' : 'river by',
'riverstone' : 'river stone',
'rivettool' : 'rivet tool',
'rizzy' : 'frizzy',
'rocksolid' : 'rock solid',
'rockwool' : 'rock wool',
'rodiron' : 'rod iron',
'rodskit' : 'rod skit',
'rollerss' : 'rollers',
'romanic' : 'romantic',
'romax' : 'roman',
'roppe' : 'rope',
'rough-in' : 'rough in',
'roughin' : 'rough in',
'rouind' : 'round',
'round-up' : 'round up',
'rounda' : 'round',
'roung' : 'round',
'rount' : 'round',
'rplacement' : 'replacement',
'rrecessed' : 'recessed',
'rrip' : 'rip',
'rubbber' : 'rubber',
'rubberaid' : 'rubber aid',
'rubbermade' : 'rubber made',
'rubiks' : 'rubies',
'ruf' : 'ryg',
'rug,' : 'rug',
'ruggs' : 'rugs',
'rugs,' : 'rugs',
'rumbl;estone' : 'cobblestone',
'ruotor' : 'rotor',
'rust-o-leum' : 'Rust-Oleum',
'rust-oleum' : 'Rust-Oleum',
'rust/ivory' : 'rust ivory',
'rusteoulm' : 'Rust-Oleum',
'rustolem' : 'Rust-Oleum',
'rustoleum' : 'Rust-Oleum',
'rustolium' : 'Rust-Oleum',
'rustollum' : 'Rust-Oleum',
'rutic' : 'rustic',
'ruunners' : 'runners',
'sae' : 'sea',
'safegaurd' : 'safeguard',
'safet' : 'safe',
'safty' : 'safety',
'sahde' : 'shade',
'sailwind' : 'sail wind',
'sammples' : 'samples',
'samsong' : 'samsung',
'samsungelectric' : 'samsung electric',
'sandard' : 'standard',
'sandpap' : 'sand pap',
'sandtone' : 'sandstone',
'saquets' : 'parquets',
'satcreek' : 'sat creek',
'savavieh' : 'savannah',
'saw\'' : 'saw',
'saw-max' : 'saw max',
'sawall' : 'seawall',
'sawd' : 'saw',
'sawshop' : 'saw shop',
'sawtrax' : 'saw',
'saww' : 'saw',
'scaleblaster' : 'scale blaster',
'sceen' : 'screen',
'scement' : 'cement',
'scerews' : 'screws',
'scews' : 'sews',
'schecule' : 'schedule',
'sched' : 'schedule',
'scheem' : 'scheme',
'scocket' : 'socket',
'scraperreplacement' : 'scraper replacement',
'screeen' : 'screen',
'screem' : 'screen',
'screrw' : 'screw',
'scret' : 'secret',
'screw-on' : 'screw on',
'screw-type' : 'screw type',
'screwa' : 'screw',
'screwes' : 'screw',
'screws,' : 'screw',
'screwsw' : 'screw',
'screww' : 'screw',
'screwws' : 'screw',
'scrool' : 'school',
'scrren' : 'screen',
'scrubbin' : 'scrubbing',
'scruby' : 'scrub',
'scrue' : 'screw',
'scub' : 'scrub',
'sculture' : 'culture',
'scurity' : 'security',
'seahawks' : 'sea hawks',
'sealent' : 'sealant',
'sealler' : 'sealant',
'sealparts' : 'seal parts',
'seat,' : 'seat',
'seatting' : 'setting',
'securemount' : 'secure mount',
'securty' : 'security',
'secutity' : 'security',
'sedgehammer' : 'sedge hammer',
'selenoid' : 'solenoid',
'self-cleaning' : 'self cleaning',
'self-closing' : 'self closing',
'self-leveling' : 'self leveling',
'self-locking' : 'self locking',
'selfstick' : 'self stick',
'sement' : 'cement',
'semi-gloss' : 'semi gloss',
'semigloass' : 'semi gloss',
'semirigid' : 'semi rigid',
'sencer' : 'sensor',
'sendero' : 'sensor',
'senser' : 'sensor',
'sensor,' : 'sensor',
'sensoring' : 'sensor',
'sensoroutdoor' : 'sensor outdoor',
'serface' : 'surface',
'seriesimpact' : 'series impact',
'seris' : 'series',
'set,' : 'set',
'settingfence' : 'setting fence',
'sewimg' : 'sewing',
'sflexible' : 'flexible',
'shades,' : 'shades',
'shafe' : 'safe',
'shakewood' : 'shake wood',
'sharkbait' : 'shark bait',
'sharkbike' : 'shark bike',
'sharkbit' : 'shark bit',
'sharkbite' : 'shark bite',
'sharkbits' : 'shark bits',
'sharpner' : 'sharper',
'sharppener' : 'sharpener',
'shed?' : 'shed',
'sheeet' : 'sheet',
'sheeti' : 'sheet',
'sheetin' : 'sheeting',
'sheetmetal' : 'sheet metal',
'sheetrock\'' : 'sheetrock',
'sheface' : 'she face',
'shefl' : 'shelf',
'shelac' : 'shellac',
'shelburne' : 'shelby',
'shelf,' : 'shelf',
'shelfa' : 'shelf',
'shelflike' : 'shelf like',
'sheliving' : 'shelving',
'shellac-based' : 'shellac',
'shels' : 'shelf',
'shelterlogic' : 'shelter logic',
'shelv' : 'shelf',
'shelvees' : 'shelf',
'shelving,' : 'shelf',
'shepards' : 'shepard',
'shere' : 'shear',
'sherpeners' : 'sharpeners',
'shesd' : 'sheds',
'shets' : 'sets',
'sheves' : 'shelf',
'shevles' : 'shelf',
'shevlving' : 'shelf',
'shigles' : 'hingles',
'shitch' : 'hitch',
'shoipping' : 'shipping',
'shopac' : 'shop ac',
'shoplight' : 'shop light',
'shopvac' : 'shop vac',
'shorebrook' : 'shore brook',
'shovles' : 'shelf',
'showe' : 'shower',
'showerhead.' : 'shower head',
'showerheards' : 'shower head',
'showerstall' : 'shower stall',
'showerstorage' : 'shower storage',
'showeruni' : 'shower unit',
'showerz' : 'shower',
'shut-off' : 'shut off',
'shutters/sunburst' : 'shutter sunburst',
'shwoer' : 'shower',
'siccsers' : 'sissors',
'siclica' : 'silica',
'sideays' : 'sideways',
'sideing' : 'siding',
'sidelits' : 'sidelights',
'sideout' : 'hideout',
'sidepanels' : 'side panels',
'sigle' : 'single',
'sikalatexr' : 'simulate',
'silca' : 'silica',
'silcock' : 'silicon',
'silcone' : 'silicone',
'silding' : 'sliding',
'silocoln' : 'silicone',
'silocone' : 'silicone',
'siloutte' : 'silhouette',
'simming' : 'slimming',
'simonton' : 'simonette',
'simpleset' : 'simplest',
'simpli' : 'simple',
'simpon' : 'simpson',
'singel' : 'single',
'sink,' : 'sink',
'sinks,' : 'sinks',
'sinl' : 'sin',
'sinnk' : 'sink',
'sipcovers' : 'slipcovers',
'sippy' : 'snippy',
'sissors' : 'scissors',
'sistem' : 'system',
'sjhelf' : 'shelf',
'skillsaw' : 'skill saw',
'skilsaw' : 'skill saw',
'skylifghts' : 'sky light',
'skylites' : 'sky light',
'slealer' : 'sealer',
'sleave' : 'leave',
'sleeveee' : 'sleeveless',
'slelves' : 'shelf',
'slide-a-shelf' : 'slide a shelf',
'slidein' : 'slide in',
'slideing' : 'sliding',
'slidng' : 'sliding',
'slidr' : 'slide',
'slimstyle' : 'slim style',
'sloted' : 'slotted',
'slyvanna' : 'savannah',
'smartstrand' : 'smart strand',
'smugde' : 'smudge',
'snap-in' : 'snap in',
'snapstone' : 'snap stone',
'snk' : 'sink',
'snowerblower' : 'snowblower',
'soap,' : 'soap',
'sod,' : 'sod',
'sodering' : 'soldering',
'sodpstone' : 'soapstone',
'sofet' : 'soft',
'softlite' : 'soft lite',
'softner' : 'softener',
'softners' : 'softeners',
'softowood' : 'soft wood',
'softspring' : 'soft spring',
'soil-mix' : 'soil mix',
'soil?' : 'soil',
'soild' : 'solid',
'solenoide' : 'solenoid',
'solidconcrete' : 'solid concrete',
'sorage' : 'storage',
'soundfroofing' : 'soundproofing',
'southren' : 'southern',
'southwire' : 'south wire',
'spacemaker' : 'space maker',
'spacks' : 'packs',
'spaint' : 'paint',
'spalsh' : 'splash',
'spalted' : 'salted',
'spaonges' : 'sponges',
'speacalty' : 'specialty',
'speader' : 'speared',
'speakman' : 'speak man',
'spectacide' : 'spectacle',
'specticide' : 'insecticide',
'spee-d' : 'speed',
'speed/light' : 'speed light',
'speedwall' : 'speed wall',
'speedzone' : 'speed zone',
'spgot' : 'spot',
'spicewood' : 'spice wood',
'spikey' : 'spiky',
'spindel' : 'spindle',
'sping' : 'spring',
'spirsl' : 'spiral',
'splach' : 'splash',
'splashback' : 'splash back',
'splenda' : 'splendor',
'split-wired' : 'split wire',
'splitbolt' : 'split bolt',
'spliter' : 'splinter',
'splt' : 'split',
'spotffree' : 'spot free',
'spoutts' : 'spouts',
'sppeed' : 'speed',
'spraypaint' : 'spray paint',
'sprayway' : 'spray way',
'spreadstone' : 'spread stone',
'spreklers' : 'sprinklers',
'sprial' : 'spiral',
'springdale' : 'spring dale',
'springes' : 'springs',
'springfield,ct' : 'springfield',
'springkler' : 'sprinkler',
'sprinler' : 'sprinkler',
'sprkinler' : 'sprinkler',
'spryer' : 'sprayer',
'sprying' : 'spraying',
'spunge' : 'sponge',
'sqeaky' : 'squeaky',
'squar' : 'square',
'squicky' : 'quick',
'srcew' : 'screw',
'srew' : 'screw',
'srewdriver' : 'screw driver',
'sschlueter' : 'schlesinger',
'sseat' : 'seat',
'stabilisor' : 'stabilizer',
'stabilty' : 'stability',
'stailess' : 'stainless',
'stain,' : 'stain',
'stainles' : 'stainless',
'stainless-steel' : 'stainless steel',
'stainlss' : 'stainless',
'stainolid' : 'stainless',
'stainstess' : 'stainless',
'stairtreads' : 'stair treads',
'stand,' : 'stand',
'standard/' : 'standard',
'starcoat' : 'star coat',
'stcking' : 'sticking',
'steamwasher' : 'steam washer',
'steeel' : 'steel',
'steel,' : 'steel',
'steele' : 'steel',
'stel' : 'steel',
'stemcartridge' : 'stem cartridge',
'steqamers' : 'steamers',
'sterilite' : 'sterilize',
'sterio' : 'stereo',
'sterlite' : 'sterling',
'stewartcabinet' : 'stewart cabinet',
'stickon' : 'stick on',
'stipper' : 'tipper',
'stiprs' : 'stirs',
'stive' : 'stove',
'stnless' : 'stainless',
'stoage' : 'storage',
'stobe' : 'strobe',
'stomr' : 'storm',
'stopwa' : 'stopwatch',
'storeage' : 'storage',
'storge' : 'store',
'strafford' : 'stratford',
'straitline' : 'strait line',
'striker/catch' : 'striker catch',
'stripoping' : 'stripping',
'strippping' : 'stripping',
'stroas' : 'strops',
'strong-tie' : 'strong tie',
'strorm' : 'storm',
'strps' : 'streps',
'strranded' : 'stranded',
'structered' : 'structured',
'structue' : 'structure',
'stuko' : 'stucco',
'styrafoam' : 'styrofoam',
'suart' : 'start',
'sub-panel' : 'sub panel',
'submerciable' : 'submersible',
'submeribale' : 'submersible',
'subpumps' : 'sub pumps',
'sucktion' : 'suction',
'sumpter' : 'stumper',
'sunbrellap' : 'umbrella',
'suncast' : 'sun cast',
'suncourt' : 'sun court',
'sunheat' : 'sun heat',
'sunjoy' : 'sun joy',
'sunlite' : 'sun lite',
'sunpatiens' : 'sun patients',
'sunstone' : 'sun stone',
'suny' : 'sun',
'suplies' : 'supplies',
'supprt' : 'support',
'supression' : 'suppression',
'surebond' : 'sure bond',
'suretest' : 'sure test',
'surfacemount' : 'surface mount',
'suround' : 'surround',
'surveilance' : 'surveillance',
'survelliance' : 'surveillance',
'susbenders' : 'suspenders',
'suspanded' : 'suspended',
'sweeep' : 'sweep',
'sweel' : 'steel',
'sweenys' : 'sweeneys',
'sweep,' : 'sweep',
'sweeperr' : 'sweeper',
'swer' : 'sewer',
'swich' : 'switch',
'swifer' : 'swifter',
'swiffer' : 'sniffer',
'swimg' : 'swim',
'swiming' : 'swimming',
'swing-n-slide' : 'swing and slide',
'switchplate' : 'switch plate',
'switcht' : 'switch',
'switchvers' : 'switchers',
'swivle' : 'swivel',
'swivrl' : 'swirl',
'syllicone' : 'silicone',
'symmetrix' : 'symmetric',
'symmons' : 'summons',
'syste,m' : 'system',
'syston' : 'system',
't-handle' : 't handle',
't-hinge' : 't hinge',
't-mould' : 't mould',
't-track' : 't track',
't.v' : 'television',
'tab;le' : 'table',
'tabel,' : 'table',
'tablrs' : 'table',
'tactiical' : 'tactical',
'takles' : 'table',
'tampe' : 'tamper',
'tamper-resistant' : 'tamper resistant',
'tankles' : 'ankles',
'tanks/' : 'tanks',
'tanks?' : 'tanks',
'tapecase' : 'tape case',
'tapeexhaust' : 'tape exhaust',
'tblades' : 'blades',
'tbricks' : 'bricks',
'tdiles' : 'tiles',
'teasure' : 'treasure',
'tefuse' : 'refuse',
'tegular' : 'regular',
'teir' : 'tier',
'telemechanic' : 'tele mechanics',
'telephone/cable' : 'telephone cable',
'telescooping' : 'telescoping',
'temperture' : 'temperature',
'templit' : 'temp lit',
'teracota' : 'terracotta',
'terminalsnylon' : 'terminals nylon',
'termometer' : 'thermometer',
'thck' : 'thick',
'theader' : 'header',
'themostat' : 'thermostat',
'theomomter' : 'thermometer',
'ther' : 'tier',
'thermacell' : 'thermal cell',
'thermalblend' : 'thermal blend',
'thermocast' : 'thermo cast',
'thermocoupler' : 'thermocouple',
'thermom' : 'thermo',
'thermost' : 'thermostat',
'thermstate' : 'thermostat',
'theromometer' : 'thermometer',
'theromsat' : 'thermostat',
'therostats' : 'thermostats',
'thewall' : 'the wall',
'thickrubber' : 'thick rubber',
'threadded' : 'threaded',
'threadlocker' : 'thread locker',
'threadrs' : 'threads',
'threashold' : 'threshold',
'threshhold' : 'threshold',
'threshholds' : 'thresholds',
'thromastate' : 'thermostat',
'tiele' : 'tile',
'tiertrolley' : 'tier trolley',
'tigerstripe' : 'tiger stripe',
'tigerwood' : 'tiger wood',
'tighrner' : 'tightener',
'tiiles' : 'tiles',
'tikles' : 'tiles',
'tile,' : 'tile',
'tilebath' : 'tile bath',
'tilecordoba' : 'tile cordoba',
'tilees' : 'tiles',
'tilekit' : 'tile kit',
'tilelab' : 'tile lab',
'tilesaw' : 'tile saw',
'tilex' : 'tile',
'tille' : 'tile',
'tilw' : 'tile',
'timberlake' : 'timber lake',
'timmer' : 'timer',
'timmers' : 'timers',
'tiolet' : 'toilet',
'tip-out' : 'tip out',
'tmolding' : 'molding',
'toelit' : 'toilet',
'togther' : 'together',
'toiet' : 'toilet',
'toiles' : 'toilet',
'toilest' : 'toilet',
'toilets,' : 'toilet',
'toillet' : 'toilet',
'toitets' : 'toilet',
'tolet' : 'toilet',
'toliet' : 'toilet',
'toliets' : 'toilet',
'tolite' : 'toilet',
'tomostat' : 'thermostat',
'tooal' : 'tool',
'tood' : 'tool',
'toold' : 'tool',
'toolsg' : 'tools',
'tootls' : 'tools',
'top,' : 'top',
'top-freezer' : 'top freezer',
'top-lock' : 'top lock',
'top/drop-in' : 'top drop in',
'topdown' : 'top down',
'toplass' : 'topless',
'topmetal' : 'top metal',
'toprail' : 'top rail',
'tops,' : 'tops',
'topsealer' : 'top sealer',
'torch-on' : 'torch on',
'tourche' : 'toucher',
'tourches' : 'torches',
'towbehind' : 'tow behind',
'towpower' : 'tow power',
'toyotaa' : 'toyota',
'tpoilet' : 'toilet',
'tracerse' : 'tracers',
'traeger' : 'tragedy',
'trafficmaster' : 'traffic master',
'traficmaster' : 'traffic master',
'traiter' : 'trailer',
'transformet' : 'transformer',
'transformr' : 'transform',
'transmissin' : 'transmission',
'transormations' : 'transformations',
'transparant' : 'transparent',
'trasure' : 'treasure',
'treaated' : 'treated',
'treate' : 'treat',
'treeted' : 'greeted',
'tremco' : 'tremor',
'trendscape' : 'trend scape',
'treshold' : 'threshold',
'tresspassing' : 'trespassing',
'tridicator' : 'eradicator',
'trimmer/edger\'s,' : 'trimmer',
'trinsic' : 'intrinsic',
'trol' : 'troll',
'trollie' : 'trolling',
'tropper' : 'topper',
'tru-infrared' : 'infrared',
'tsnkless' : 'tankless',
'tub/hand' : 'tub hand',
'tub/shower' : 'tub shower',
'tuband' : 'tub and',
'tubeing' : 'tube',
'tubn' : 'tub',
'tuffscreen' : 'tuff screen',
'two-piece' : '2 piece',
'two-stage' : '2 stage',
'two/three' : 'two three',
'tyhoon' : 'typhoon',
'tyvek' : 'tyke',
'u-bolt' : 'u bolt',
'u-bolts' : 'u bolts',
'u-shape' : 'u shape',
'uard' : 'guard',
'ultratouch' : 'ultra touch',
'ultrta' : 'ultra',
'umbella' : 'umbrella',
'umbrell' : 'umbrella',
'un-finished' : 'unfinished',
'unbralla' : 'umbrella',
'unbrella' : 'umbrella',
'undelayment' : 'under layment',
'underbed' : 'under bed',
'underdeck' : 'under deck',
'undergroud' : 'underground',
'underhood' : 'under hood',
'underpenning' : 'under pinning',
'underthe' : 'under the',
'unfinish' : 'unfinished',
'unfinushed' : 'unfinished',
'unger' : 'under',
'unidoor' : 'uni door',
'uniflame' : 'uni flame',
'unistruct' : 'uni struct',
'unjit' : 'unit',
'unmbrella' : 'umbrella',
'unmortified' : 'unmodifited',
'unsulation' : 'insulation',
'untility' : 'utility',
'untique' : 'antique',
'up/down' : 'up down',
'upholstry' : 'upholstery',
'uplihght' : 'up light',
'upsidedowncan' : 'up side down',
'urathane' : 'urethane',
'urehtane' : 'urethane',
'usb/multi-outlet' : 'use multi outlet',
'utdriver' : 'driver',
'v-belt' : 'v belt',
'v-ramp' : 'y ramp',
'vaccume' : 'vacuum',
'vaccumm' : 'vacuum',
'vaccuum' : 'vacuum',
'vacum' : 'vacuum',
'vacum,' : 'vacuum',
'vacume' : 'vacuum',
'vacumm' : 'vacuum',
'vacumns' : 'vacuums',
'vacuum,' : 'vacuum',
'vainty' : 'vanity',

'valnity' : 'vanity',
'valted' : 'vaulted',
'valv' : 'valve',
'valve,' : 'valve',
'valvefor' : 'valve for',
'valvez' : 'valve',
'valvu' : 'valve',
'valvue' : 'valve',
'valvule' : 'valvular',
'vaneer' : 'veneer',
'vaniteis' : 'vanities',
'vanites' : 'vanities',
'vanitiy' : 'vanity',
'vanyl' : 'vinyl',
'vaporbarrier,' : 'vapor barrier',
'varigated' : 'variated',
'varnishe' : 'varnish',
'vauhhan' : 'vaughan',
'vbration' : 'vibration',
'veclro' : 'velcro',
'veeneer' : 'veneer',
'veener' : 'veneer',
'vegetale' : 'vegetable',
'vegtable' : 'vegetable',
'ventalation' : 'ventilation',
'ventiliation' : 'ventilation',
'ventss' : 'vents',
'verneer' : 'veneer',
'vero' : 'verso',
'versabon' : 'versabond',
'versabond' : 'versabond',
'versabone' : 'versabond',
'versatiube' : 'versa tube',
'versi' : 'verse',
'vesel' : 'vessel',
'vessal' : 'vessel',
'vessell' : 'vessel',
'vessona' : 'vessel',
'vetical' : 'vertical',
'vinotemp' : 'vino temp',
'vintemp' : 'vintage',
'viny' : 'vinyl',
'vinyl,' : 'vinyl',
'vinyl-coated' : 'vinyl coated',
'vinylcorner' : 'vinyl corner',
'vinylcove' : 'vinyl cove',
'vinyle' : 'vinyl',
'virginai' : 'virginal',
'virtu' : 'virtue',
'viyl' : 'vinyl',
'viyle' : 'vinyl',
'viynl' : 'vinyl',
'vlave' : 'valve',
'vlaves' : 'valves',
'vlve' : 'valve',
'vlyvynal' : 'vinyl',
'vnyl' : 'vinyl',
'vynil' : 'vinyl',
'w/ground' : 'with ground',
'w/nails' : 'with nails',
'w/seat' : 'with seat',
'w/shelves' : 'with shelves',
'w/sidelites' : 'with sidelights',
'w/spray' : 'with spray',
'waater' : 'water',
'wadrobe' : 'wardrobe',
'waher' : 'washer',
'wahing' : 'washing',
'walk-in' : 'walk in',
'walkbehind' : 'walk behind',
'wall-mount' : 'wall mount',
'wall/bath' : 'wall bath',
'wall/ceiling' : 'wall ceiling',
'wallhugger' : 'wall hunger',
'walll' : 'wall',
'walloven' : 'wall oven',
'wallpanel' : 'wall panel',
'wallplate,' : 'wall plate',
'wallpops' : 'wall pops',
'wallprimer' : 'wall primer',
'walnuit' : 'walnut',
'walnut/new' : 'walnut new',
'warmlight' : 'warm light',
'washer,' : 'washer',
'washer-' : 'washer',
'washer/dryr' : 'washer dryer',
'washer/top' : 'washerwomen',
'washerparts' : 'washer parts',
'washign' : 'washing',
'wastel' : 'waste',
'waterheater' : 'water heater',
'waterpik' : 'water',
'waterproff' : 'waterproof',
'waterpump' : 'water pump',
'waterroo' : 'water',
'waterseal' : 'water seal',
'wateting' : 'watering',
'watherproof' : 'weather proof',
'watt,' : 'watt',
'watterproof' : 'waterproof',
'wattsolar' : 'watt solar',
'weall' : 'wall',
'weatherhead' : 'weather head',
'weathershield' : 'weather shield',
'weathertech' : 'weather tech',
'weedeater' : 'weed eater',
'weedeaters' : 'weed eaters',
'weelbarrow' : 'wheelbarrow',
'well\'' : 'well',
'wellworth' : 'well worth',
'westlock' : 'west lock',
'wet/dry' : 'wet dry',
'wetbar' : 'wet bar',
'wexford' : 'oxford',
'whearehoues' : 'warehouses',
'wheelb' : 'wheel',
'wheelbarow' : 'wheelbarrow',
'wheeld' : 'wheel',
'whellbarrow' : 'wheelbarrow',
'whilrpool' : 'whirlpool',
'whirlpoolgas' : 'whirlpool gas',
'whirlpoolstainless' : 'whirlpool stainless',
'whirpool' : 'whirlpool',
'white,' : 'white',
'whitecomposite' : 'white composite',
'whitehaven' : 'white haven',
'whitel' : 'white',
'whiteled' : 'whittled',
'whitesilicone' : 'white silicone',
'whithaus' : 'whithers',
'whtie' : 'white',
'wi-fi' : 'winfield',
'widecellular' : 'wide cellular',
'wiemans' : 'wiemar',
'wihite' : 'white',
'windowair' : 'window air',
'windowbalance' : 'window balance',
'windoww' : 'window',
'windser' : 'winder',
'wireing' : 'wiring',
'wirell' : 'wire',
'wiremesh' : 'wire mesh',
'wiremold' : 'wire mold',
'wirenuts' : 'wire nuts',
'wirerless' : 'wireless',
'wirless' : 'wireless',
'wirlpool' : 'whirlpool',
'wjth' : 'with',
'wndow' : 'window',
'wndows' : 'windows',
'wod' : 'wood',
'woltage' : 'voltage',
'wondow' : 'window',
'wood,' : 'wood',
'wood,pine,' : 'wood pine',
'wood-burning' : 'wood burning',
'wood/metal' : 'wood metal',
'woodceramic' : 'wood ceramic',
'woodcrafters' : 'woodcrafts',
'woodebn' : 'wooden',
'woodflooring' : 'wood flooring',
'woodford' : 'wood ford',
'woodmark' : 'wood mark',
'woodrx' : 'wood',
'woodsaddle' : 'wood saddle',
'woodwen' : 'wooden',
'worklite' : 'work lite',
'workpro' : 'work pro',
'workstar' : 'work star',
'worksurface' : 'work surface',
'workx' : 'work',
'worldpool' : 'world pool',
'wwod' : 'wood',
'xbox' : 'box',
'xhose' : 'hose',
'y-connector' : 'y connector',
'yardwaste' : 'yard waste',
'yeaer' : 'year',
'yelloe' : 'yellow',
'zeroturn' : 'zero turn',
'zinc-plated' : 'zinc plated',
'zinser' : 'rinser',
'zinsser' : 'rinser',
'zise' : 'size',
'zo' : 'oz',
'zwave' : 'wave',
'\'molded' : 'molded',
'\'pellet' : 'pellet',
'\'rip' : 'rip',
'\'wash' : 'wash',
'\'water' : 'water',
',cat,repellant' : 'cat repellent',
',mohawk' : 'mohawk',
'-appliance' : 'appliance',
'-door' : 'door',
'-fan' : 'fan',
'-flexidip' : 'flexidip',
'/heater' : 'heater',
'/heaterconditioner' : 'heater conditioner',
'a/c' : 'air conditioner',
}




RE_D = re.compile('\d')
def hasDigits(string):
    return RE_D.search(string)

# tokeniser = re.compile("(?:[A-Za-z]{1,2}\.)+|[\w\']+|\.\.\.|\?\!")
# def homedepotTokeniser(string):
#     return tokeniser.findall(string)

if __name__ == "__main__":
    train_filename = '../../data/train.csv'
    test_filename = '../../data/test.csv'
    attribute_filename = '../../data/attributes.csv'
    description_filename = '../../data/product_descriptions.csv'

    reader = HomeDepotReader()
    train_query_df, product_df, attribute_df, test_query_df = reader.getQueryProductAttributeDataFrame(train_filename,
                                                  test_filename,
                                                  attribute_filename,
                                                  description_filename)

    vocab = defaultdict(int)
    for s in product_df.product_title:
        # no_punctuation = s.translate(None, string.punctuation)
        # token = nltk.word_tokenize(s)
        token = FeatureEngineering.homedepotTokeniser(s)
        # token = s.lower().split(' ')
        # print(s)
        for t in token:
            # print(t)
            vocab[str(t)] += 1

    for s in product_df.product_description:
        # token = s.lower().split(' ')
        # token = nltk.word_tokenize(s)
        token = FeatureEngineering.homedepotTokeniser(s)
        for t in token:
            vocab[str(t)] += 1

    brand_df = attribute_df[attribute_df.name == "MFG Brand Name"][['product_uid', 'value']]
    brand_df.rename(columns={'value': 'product_brand'}, inplace=True)
    product_df = pd.merge(product_df, brand_df, how='left', on='product_uid')

    for s in product_df.product_brand:
        # token = s.lower().split(' ')
        # token = nltk.word_tokenize(s)
        token = FeatureEngineering.homedepotTokeniser(str(s))
        for t in token:
            vocab[str(t)] += 1

    for s in attribute_df.value:
        # token = s.lower().split(' ')
        # token = nltk.word_tokenize(s)
        token = FeatureEngineering.homedepotTokeniser(str(s))
        for t in token:
            vocab[str(t)] += 1

    print(len(vocab))
    keys = list(vocab.keys())
    # print(keys[:100])

    df = pd.DataFrame(keys)

    HomeDepotCSVWriter().dumpCSV(df, "../../data/homedepot_vocab.txt", False)
    print("Dumped CSV")

    d = enchant.DictWithPWL("en_US", '../../data/homedepot_vocab.txt')
    all_df = pd.concat((train_query_df, test_query_df), axis=0, ignore_index=True)
    n = 0
    dict = {}
    for s in all_df.search_term:
        token = s.split(" ")
        # print(str(n) + " " + str(d.check(token)))
        for t in token:
            if len(t)!= 0:
                if not hasDigits(t):
                    if d.check(t)==False:
                        if t not in dict:
                            suggest = d.suggest(t)
                            if len(suggest)>0:
                                dict[t] = suggest[0]
                                # print("'" + t + "' : '" + suggest[0] + "',")
                            else:
                                dict[t] = ''
                                # print("'" + t + "' : '',")

            n+=1

    print("Length all: ", n)
    print("Length of dict: ", len(dict))

    for k, v in dict.items():
        print("'" + k + "' : '" + v + "',")

    n = 0
    sortedkey = sorted(spell_dict)
    for k in sortedkey:
        if spell_dict[k].lower() != k.lower():
            print("'" + k.lower() + "' : '" + spell_dict[k].lower() + "',")
        else:
            n+=1

    for t in keys:
        if str(t).lower() in spell_dict:
            del spell_dict[str(t).lower()]
            n+=1

    print("Removed: ", n)